### ISSUE TITLE
更新代码后 登录页换肤按钮消失了

### ISSUE THREAD

**Issue by MrZhuA00** [1421788142/WAdmin#1]
![image](https://user-images.githubusercontent.com/102725920/224866810-2f5c9df5-d329-4d13-9854-37f68d9abac4.png)

**Comment by MrZhuA00** [comment]
是给删掉了吗

**Comment by 1421788142** [comment]
之前有问题 现在已重新加上了

**Comment by 1421788142** [comment]
> 是给剪掉了吗

已重新加上了
